### PR TITLE
Fixed vuetify media query size. Updated both vuetify and bootstrap query to support XL breakpoint

### PR DESCRIPTION
**Pull request by hxiongg**
Updated metrics to better reflect what is documented by vuetify 
https://vuetifyjs.com/layout/grid

Vuetify is further subjected to change as it is not the breakpoints defined by Google Material Design Spec as raised here
https://github.com/vuetifyjs/vuetify/issues/391

### CODE REVIEW

**Comment by jofftiquez** [comment]
Hello @Huixiong91 great stuff! Thanks for your work. Much appreciated. Have you tested this on your end? Coz this will surely break things around.

**Comment by hxiongg** [comment]
@jofftiquez 
Hi yes, tested this. Nothing disruptive to current users of this library, just different (more accurate) breakpoints to the respective UI Framework they specify.

**Comment by jofftiquez** [comment]
@Huixiong91 great then! Thank you for your pull request. :)

**Comment by jofftiquez** [comment]
I'll this to the new npm build later.

**Pull request merged**
